// File generated by FlutterFire CLI.
// The FlutterFire CLI is an extension of the Firebase CLI. Although it can be
// run independently, it is recommended to use the Firebase CLI for a more
// comprehensive experience.
// To learn more about the Firebase CLI, visit
// https://firebase.google.com/docs/cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfXi6ReOQ24HqQ3Z44z7vOn8C2W5CdgHY',
    appId: '1:736840717050:android:af1c6861e05b8698596f43',
    messagingSenderId: '736840717050',
    projectId: 'ibadah-mate',
    storageBucket: 'ibadah-mate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfXi6ReOQ24HqQ3Z44z7vOn8C2W5CdgHY',
    appId: '1:736840717050:ios:92343f7abd0c2133596f43',
    messagingSenderId: '736840717050',
    projectId: 'ibadah-mate',
    storageBucket: 'ibadah-mate.firebasestorage.app',
    iosBundleId: 'com.example.ibadahMate',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfXi6ReOQ24HqQ3Z44z7vOn8C2W5CdgHY',
    appId: '1:736840717050:web:396d47fef8f021d3596f43',
    messagingSenderId: '736840717050',
    projectId: 'ibadah-mate',
    authDomain: 'ibadah-mate.firebaseapp.com',
    storageBucket: 'ibadah-mate.firebasestorage.app',
  );
}
